name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Walidacja PR - musi przejść przed merge
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Pobierz pełną historię dla lepszego diff
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # Sprawdź czy kod się kompiluje
    - name: Type check
      run: npm run lint
    
    # Uruchom testy jednostkowe
    - name: Run unit tests
      run: npm run test:run
    
    # Sprawdź czy build działa
    - name: Build check
      run: npm run build
    
    # Sprawdź czy nie ma konfliktów
    - name: Check for merge conflicts
      run: |
        if git merge-tree $(git merge-base HEAD main) HEAD main | grep -q '<<<<<<<'; then
          echo "Merge conflicts detected"
          exit 1
        fi
    
    # Sprawdź rozmiar bundle (opcjonalnie)
    - name: Bundle size check
      run: |
        npm run build
        du -sh dist/
        # Sprawdź czy bundle nie jest większy niż 2MB
        if [ $(du -s dist/ | cut -f1) -gt 2048 ]; then
          echo "Bundle size too large (>2MB)"
          exit 1
        fi

  # Testy E2E tylko dla ważnych PR
  e2e-validation:
    runs-on: ubuntu-latest
    needs: validate
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Pobierz pełną historię dla lepszego wykrywania zmian
        fetch-depth: 0
    
    # Wykryj zmiany w plikach
    - name: Check for changes
      id: changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          src:
            - 'src/**'
    
    # Sprawdź czy PR ma label 'needs-e2e'
    - name: Check for needs-e2e label
      id: label-check
      run: |
        if echo '${{ toJson(github.event.pull_request.labels.*.name) }}' | grep -q 'needs-e2e'; then
          echo "has-label=true" >> $GITHUB_OUTPUT
        else
          echo "has-label=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Setup Node.js
      # Uruchom tylko jeśli są zmiany w src/ lub jest label 'needs-e2e'
      if: steps.changes.outputs.src == 'true' || steps.label-check.outputs.has-label == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      if: steps.changes.outputs.src == 'true' || steps.label-check.outputs.has-label == 'true'
      run: npm ci
    
    - name: Install Playwright browsers
      if: steps.changes.outputs.src == 'true' || steps.label-check.outputs.has-label == 'true'
      run: npx playwright install --with-deps
    
    - name: Run E2E tests
      if: steps.changes.outputs.src == 'true' || steps.label-check.outputs.has-label == 'true'
      run: npm run test:e2e
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure() && (steps.changes.outputs.src == 'true' || steps.label-check.outputs.has-label == 'true')
      with:
        name: e2e-test-results
        path: |
          playwright-report/
          test-results/
