name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Walidacja PR - musi przejść przed merge
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Pobierz pełną historię dla lepszego diff
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # Sprawdź czy kod się kompiluje
    - name: Type check
      run: npm run lint
    
    # Uruchom testy jednostkowe
    - name: Run unit tests
      run: npm run test:run
    
    # Sprawdź czy build działa
    - name: Build check
      run: npm run build
    
    # Sprawdź czy nie ma konfliktów
    - name: Check for merge conflicts
      run: |
        if git merge-tree $(git merge-base HEAD main) HEAD main | grep -q '<<<<<<<'; then
          echo "Merge conflicts detected"
          exit 1
        fi
    
    # Sprawdź rozmiar bundle (opcjonalnie)
    - name: Bundle size check
      run: |
        npm run build
        du -sh dist/
        # Sprawdź czy bundle nie jest większy niż 2MB
        if [ $(du -s dist/ | cut -f1) -gt 2048 ]; then
          echo "Bundle size too large (>2MB)"
          exit 1
        fi

