name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Walidacja PR - musi przejść przed merge
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Pobierz pełną historię dla lepszego diff
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # Sprawdź czy kod się kompiluje
    - name: Type check
      run: npm run lint
    
    # Uruchom testy jednostkowe
    - name: Run unit tests
      run: npm run test:run
    
    # Sprawdź czy build działa
    - name: Build check
      run: npm run build
    
    # Sprawdź czy nie ma konfliktów
    - name: Check for merge conflicts
      run: |
        echo "Checking for merge conflicts with main branch..."
        
        # Sprawdź czy main branch istnieje
        if ! git show-ref --verify --quiet refs/remotes/origin/main; then
          echo "Warning: main branch not found, skipping merge conflict check"
          exit 0
        fi
        
        # Znajdź wspólny ancestor
        if ! MERGE_BASE=$(git merge-base HEAD origin/main 2>/dev/null); then
          echo "Warning: No common ancestor found between HEAD and main, skipping conflict check"
          exit 0
        fi
        
        echo "Common ancestor: $MERGE_BASE"
        
        # Użyj git merge-tree do sprawdzenia konfliktów
        # Wersja z --write-tree zwraca kod błędu gdy są konflikty
        if ! git merge-tree --write-tree $MERGE_BASE HEAD origin/main >/dev/null 2>&1; then
          echo "❌ Merge conflicts detected between current branch and main!"
          echo ""
          echo "To resolve conflicts locally:"
          echo "1. git fetch origin"
          echo "2. git merge origin/main"
          echo "3. Resolve conflicts manually"
          echo "4. git add . && git commit"
          echo "5. git push"
          exit 1
        fi
        
        echo "✅ No merge conflicts detected"
    
    # Sprawdź rozmiar bundle (opcjonalnie)
    - name: Bundle size check
      run: |
        npm run build
        du -sh dist/
        # Sprawdź czy bundle nie jest większy niż 2MB
        if [ $(du -s dist/ | cut -f1) -gt 2048 ]; then
          echo "Bundle size too large (>2MB)"
          exit 1
        fi

